/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoryRenderImport } from './routes/story-render'
import { Route as SearchEnginesImport } from './routes/_search-engines'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSearchEnginesImport } from './routes/_layout/search-engines'
import { Route as SearchEnginesSearchEnginesApplyImport } from './routes/_search-engines/search-engines.apply'
import { Route as SearchEnginesSearchEnginesIdImport } from './routes/_search-engines/search-engines.$id'

// Create/Update Routes

const StoryRenderRoute = StoryRenderImport.update({
  id: '/story-render',
  path: '/story-render',
  getParentRoute: () => rootRoute,
} as any)

const SearchEnginesRoute = SearchEnginesImport.update({
  id: '/_search-engines',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchEnginesRoute = LayoutSearchEnginesImport.update({
  id: '/search-engines',
  path: '/search-engines',
  getParentRoute: () => LayoutRoute,
} as any)

const SearchEnginesSearchEnginesApplyRoute =
  SearchEnginesSearchEnginesApplyImport.update({
    id: '/search-engines/apply',
    path: '/search-engines/apply',
    getParentRoute: () => SearchEnginesRoute,
  } as any)

const SearchEnginesSearchEnginesIdRoute =
  SearchEnginesSearchEnginesIdImport.update({
    id: '/search-engines/$id',
    path: '/search-engines/$id',
    getParentRoute: () => SearchEnginesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_search-engines': {
      id: '/_search-engines'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SearchEnginesImport
      parentRoute: typeof rootRoute
    }
    '/story-render': {
      id: '/story-render'
      path: '/story-render'
      fullPath: '/story-render'
      preLoaderRoute: typeof StoryRenderImport
      parentRoute: typeof rootRoute
    }
    '/_layout/search-engines': {
      id: '/_layout/search-engines'
      path: '/search-engines'
      fullPath: '/search-engines'
      preLoaderRoute: typeof LayoutSearchEnginesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_search-engines/search-engines/$id': {
      id: '/_search-engines/search-engines/$id'
      path: '/search-engines/$id'
      fullPath: '/search-engines/$id'
      preLoaderRoute: typeof SearchEnginesSearchEnginesIdImport
      parentRoute: typeof SearchEnginesImport
    }
    '/_search-engines/search-engines/apply': {
      id: '/_search-engines/search-engines/apply'
      path: '/search-engines/apply'
      fullPath: '/search-engines/apply'
      preLoaderRoute: typeof SearchEnginesSearchEnginesApplyImport
      parentRoute: typeof SearchEnginesImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutSearchEnginesRoute: typeof LayoutSearchEnginesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSearchEnginesRoute: LayoutSearchEnginesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface SearchEnginesRouteChildren {
  SearchEnginesSearchEnginesIdRoute: typeof SearchEnginesSearchEnginesIdRoute
  SearchEnginesSearchEnginesApplyRoute: typeof SearchEnginesSearchEnginesApplyRoute
}

const SearchEnginesRouteChildren: SearchEnginesRouteChildren = {
  SearchEnginesSearchEnginesIdRoute: SearchEnginesSearchEnginesIdRoute,
  SearchEnginesSearchEnginesApplyRoute: SearchEnginesSearchEnginesApplyRoute,
}

const SearchEnginesRouteWithChildren = SearchEnginesRoute._addFileChildren(
  SearchEnginesRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof SearchEnginesRouteWithChildren
  '/story-render': typeof StoryRenderRoute
  '/search-engines': typeof LayoutSearchEnginesRoute
  '/': typeof LayoutIndexRoute
  '/search-engines/$id': typeof SearchEnginesSearchEnginesIdRoute
  '/search-engines/apply': typeof SearchEnginesSearchEnginesApplyRoute
}

export interface FileRoutesByTo {
  '': typeof SearchEnginesRouteWithChildren
  '/story-render': typeof StoryRenderRoute
  '/search-engines': typeof LayoutSearchEnginesRoute
  '/': typeof LayoutIndexRoute
  '/search-engines/$id': typeof SearchEnginesSearchEnginesIdRoute
  '/search-engines/apply': typeof SearchEnginesSearchEnginesApplyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_search-engines': typeof SearchEnginesRouteWithChildren
  '/story-render': typeof StoryRenderRoute
  '/_layout/search-engines': typeof LayoutSearchEnginesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_search-engines/search-engines/$id': typeof SearchEnginesSearchEnginesIdRoute
  '/_search-engines/search-engines/apply': typeof SearchEnginesSearchEnginesApplyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/story-render'
    | '/search-engines'
    | '/'
    | '/search-engines/$id'
    | '/search-engines/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/story-render'
    | '/search-engines'
    | '/'
    | '/search-engines/$id'
    | '/search-engines/apply'
  id:
    | '__root__'
    | '/_layout'
    | '/_search-engines'
    | '/story-render'
    | '/_layout/search-engines'
    | '/_layout/'
    | '/_search-engines/search-engines/$id'
    | '/_search-engines/search-engines/apply'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SearchEnginesRoute: typeof SearchEnginesRouteWithChildren
  StoryRenderRoute: typeof StoryRenderRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SearchEnginesRoute: SearchEnginesRouteWithChildren,
  StoryRenderRoute: StoryRenderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/_search-engines",
        "/story-render"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/search-engines",
        "/_layout/"
      ]
    },
    "/_search-engines": {
      "filePath": "_search-engines.tsx",
      "children": [
        "/_search-engines/search-engines/$id",
        "/_search-engines/search-engines/apply"
      ]
    },
    "/story-render": {
      "filePath": "story-render.tsx"
    },
    "/_layout/search-engines": {
      "filePath": "_layout/search-engines.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_search-engines/search-engines/$id": {
      "filePath": "_search-engines/search-engines.$id.tsx",
      "parent": "/_search-engines"
    },
    "/_search-engines/search-engines/apply": {
      "filePath": "_search-engines/search-engines.apply.tsx",
      "parent": "/_search-engines"
    }
  }
}
ROUTE_MANIFEST_END */
