name: review

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: pnpm
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.4.0
      - run: pnpm install
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
      - run: pnpm run typecheck

  biome:
    name: runner / biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.19.0"
          cache: pnpm
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.4.0
      - run: pnpm install
      - name: Run Biome with reviewdog
        uses: mongolyy/reviewdog-action-biome@v2.3.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
      - run: pnpm run lint
