on:
  push:
    branches:
      - main
  pull_request:

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.17.1"
          cache: "pnpm"
      - run: pnpm install
      - id: playwright_version
        run: |
          echo "playwright_version=$(pnpm why playwright --json | jq -r '.[0].devDependencies.playwright.version')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: '~/.cache/ms-playwright'
          key: ${{ runner.os }}-moon-${{ steps.playwright_version.outputs.playwright_version }}
      - run: pnpx playwright install chromium --with-deps

      - uses: actions/cache@v4
        with:
          path: .moon/cache
          key: ${{ runner.os }}-moon
      - run: pnpm test
